language: r
sudo: false

cache:
  packages: true

before_install:
  # install libudunits2
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -q update
  - sudo apt-get -y install libudunits2-dev
  
addons:
  apt:
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
      - netcdf-bin
      - libnetcdf-dev

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat "/home/travis/build/earthlab/cft/cft.Rcheck/*check.log"
