language: r
dist: bionic

addons:
  apt:
    packages:
      - libnetcdf-dev
      - libgdal-dev

cache:
  packages: true

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat "/home/travis/build/earthlab/cft/cft.Rcheck/*check.log"
