language: r
sudo: false
dist: bionic

addons:
  apt:
    sources:
      - ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
      - netcdf-bin
      - libnetcdf-dev

cache:
  packages: true

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat "/home/travis/build/earthlab/cft/cft.Rcheck/*check.log"
