language: r
sudo: false
cache: packages

r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - python2.7
      - python3
      - python-numpy
      - python-scipy
      - python-virtualenv
      - python3-venv
      
