on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6'}
          - {os: macOS-latest, r: '3.6'}
          - {os: ubuntu-18.04,   r: 'devel'}
          - {os: ubuntu-18.04,   r: 'release'}
          - {os: ubuntu-18.04,   r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: install macOS system dependencies
        if: runner.os == 'macOS'
        continue-on-error: true
        run: |
          brew install gdal netcdf
          
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ppa
          sudo apt-get -y update
          sudo apt-get install -y --no-install-recommends \
            libudunits2-dev \
            libproj-dev \
            libgeos-dev \
            libgdal-dev \
            netcdf-bin \ 
            libcurl-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "ggplot2"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      
      - name: Install package
        run: R CMD INSTALL .
        shell: bash -l {0}
      
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
